apiVersion: v1
kind: Service
metadata:
  name: dotnet8-api
  namespace: customer-portal
  labels:
    app: dotnet8-api
spec:
  type: NodePort
  selector:
    app: dotnet8-api
  ports:
    - name: http
      port: 5100
      targetPort: 5100
      nodePort: 25100
