version: '3.8'

services:
  django-api:
    build: .
    container_name: django-api
    ports:
      - "${PORT:-8001}:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - .:/app
    restart: unless-stopped