apiVersion: v1
kind: Service
metadata:
  name: php-web
  namespace: customer-portal
  labels:
    app: php-web
spec:
  type: ClusterIP
  selector:
    app: php-web
  ports:
    - name: http
      port: 80
      targetPort: 80
