apiVersion: v1
kind: Service
metadata:
  name: php-web
  namespace: customer-portal
  labels:
    app: php-web
spec:
  type: NodePort
  selector:
    app: php-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30002
