apiVersion: v1
kind: Service
metadata:
  name: django-web
  namespace: customer-portal
  labels:
    app: django-web
spec:
  type: NodePort
  selector:
    app: django-web
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30001
