apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: signoz

resources:
  - namespace.yaml
  - config.yaml
  - clickhouse-deployment.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: signoz
  app.kubernetes.io/managed-by: argocd
