apiVersion: v1
kind: Service
metadata:
  name: signoz
  namespace: signoz
  labels:
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30301
      protocol: TCP
    - name: internal
      port: 8085
      targetPort: 8085
      protocol: TCP
    - name: opamp
      port: 4320
      targetPort: 4320
      protocol: TCP
  selector:
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
