apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - prometheus-crd-installer-job.yaml
  - grafana-secrets.yaml
  - grafana-provisioning.yaml
  - grafana-dashboard-configmap.yaml
  - cloudnativepg-dashboard-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-rbac.yaml
  - cnpg-prometheus-rules.yaml
  - postgres-exporter-secret.yaml
  - postgres-exporter-deployment.yaml
  - postgres-exporter-service.yaml
