apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: grafana
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.15.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-exporter-credentials
                  key: datasource_user
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-exporter-credentials
                  key: datasource_password
            - name: DATA_SOURCE_NAME
              value: "postgresql://$(DATASOURCE_USER):$(DATASOURCE_PASSWORD)@django-postgres-rw.postgres-operator.svc.cluster.local:5432/django?sslmode=disable"
          ports:
            - containerPort: 9187
              name: metrics
