apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-credentials
  namespace: grafana
type: Opaque
stringData:
  datasource_name: postgres
  datasource_user: django
  datasource_password: changeme
