apiVersion: v1
kind: ConfigMap
metadata:
  name: php-api-config
  namespace: customer-portal
data:
  PORT: "8082"

---
apiVersion: v1
kind: Secret
metadata:
  name: php-api-secret
  namespace: customer-portal
type: Opaque
stringData:
  KEYCLOAK_CERT_URL: "https://s02.iampm.online/realms/master/protocol/openid-connect/certs"
  KEYCLOAK_ISSUER: "https://s02.iampm.online/realms/master"
  KEYCLOAK_AUDIENCE: "account"
  KEYCLOAK_JWKS_CACHE_SECONDS: "3600"
