apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-api
  namespace: customer-portal
  labels:
    app: php-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-api
  template:
    metadata:
      labels:
        app: php-api
    spec:
      containers:
        - name: php-api
          image: docker.io/beamblackdragon/php-api:f9c653c
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: php-api-config
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
