services:
  web:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - customnet
networks:
  customnet:
    name: customnet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
