apiVersion: v1
kind: ConfigMap
metadata:
  name: svelte-portal-config
  namespace: customer-portal
data:
  NODE_ENV: "production"
  PROXY_BASE_URL: "http://<NODE_IP>:32003"
  APP_DJANGO_URL: "http://<NODE_IP>:32003/django"
  APP_DOTNET_URL: "http://<NODE_IP>:32003/dotnet"
  APP_PHP_URL: "http://<NODE_IP>:32003/php"
  API_PHP_URL: "http://<NODE_IP>:32003/php/api/weather/london"
  API_DJANGO_URL: "http://<NODE_IP>:32003/django/api/weather/bangkok"

---
apiVersion: v1
kind: Secret
metadata:
  name: svelte-portal-secret
  namespace: customer-portal
type: Opaque
stringData:
  OAUTH_CLIENT_ID: "sample-customer-portal"
  OAUTH_CLIENT_SECRET: "yuIlwOx415U4SVab2yqB8eiA9Lqn7TPc"
  OAUTH_ISSUER: "https://s02.iampm.online/realms/master"
  OAUTH_REDIRECT_URI: "http://<NODE_IP>:32003/auth/callback"
