apiVersion: v1
kind: ConfigMap
metadata:
  name: svelte-portal-config
  namespace: customer_portal
data:
  NODE_ENV: "production"
  APP_DJANGO_URL: "http://django.customer_portal.svc.cluster.local:8000"
  APP_DOTNET_URL: "http://dotnet.customer_portal.svc.cluster.local:5000"
  APP_PHP_URL: "http://php.customer_portal.svc.cluster.local:8080"
  API_PHP_URL: "http://php.customer_portal.svc.cluster.local:8082/api/weather/london"
  API_DJANGO_URL: "http://django.customer_portal.svc.cluster.local:8000/api/weather/bangkok"

---
apiVersion: v1
kind: Secret
metadata:
  name: svelte-portal-secret
  namespace: customer_portal
type: Opaque
stringData:
  OAUTH_CLIENT_ID: "sample-customer-portal"
  OAUTH_CLIENT_SECRET: "yuIlwOx415U4SVab2yqB8eiA9Lqn7TPc"
  OAUTH_ISSUER: "https://s02.iampm.online/realms/master"
  OAUTH_REDIRECT_URI: "http://<NODE_IP>:23000/auth/callback"
