apiVersion: v1
kind: Service
metadata:
  name: svelte-portal
  namespace: customer-portal
  labels:
    app: svelte-portal
spec:
  type: ClusterIP
  selector:
    app: svelte-portal
  ports:
    - name: http
      port: 3000
      targetPort: 3000
