version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      # optional: mount source for quick dev iteration
      - ./:/src
